tms_rest:
    default_configuration:
        pagination_limit:
            default: 0
            maximum: 100
    rest_templates__get_templates:
        pagination_limit:
            default: 3
            maximum: 5
