tms_rest:
    default_configuration:
        pagination_limit:
            default: 1
            maximum: 5
    rest_templates__get_templates:
        pagination_limit:
            default: 3
            maximum: 5
