services:
    tms_rest.formatter.provider.array:
        class: Tms\Bundle\RestBundle\Formatter\Provider\ArrayHypermediaFormatterProvider
        arguments:
            - @router
            - @jms_serializer
            - @fos_rest.routing.loader.controller
            - @tms_rest.request.param_reader_provider
            - @tms_rest.request.provider
        tags:
            - { name: tms_rest.formatter.provider, id: array }

    tms_rest.formatter.provider.item:
        class: Tms\Bundle\RestBundle\Formatter\Provider\DoctrineItemHypermediaFormatterProvider
        arguments:
            - @router
            - @jms_serializer
            - @fos_rest.routing.loader.controller
            - @tms_rest.request.param_reader_provider
            - @tms_rest.request.provider
        tags:
            - { name: tms_rest.formatter.provider, id: item }

    tms_rest.formatter.provider.orm_collection:
        class: Tms\Bundle\RestBundle\Formatter\Provider\DoctrineOrmCollectionHypermediaFormatterProvider
        arguments:
            - @router
            - @jms_serializer
            - @fos_rest.routing.loader.controller
            - @tms_rest.request.param_reader_provider
            - @tms_rest.request.provider
        tags:
            - { name: tms_rest.formatter.provider, id: orm_collection }

    tms_rest.formatter.provider.mongodb_collection:
        class: Tms\Bundle\RestBundle\Formatter\Provider\DoctrineMongoDbCollectionHypermediaFormatterProvider
        arguments:
            - @router
            - @jms_serializer
            - @fos_rest.routing.loader.controller
            - @tms_rest.request.param_reader_provider
            - @tms_rest.request.provider
        tags:
            - { name: tms_rest.formatter.provider, id: mongodb_collection }

    tms_rest.formatter.provider.info:
        class: Tms\Bundle\RestBundle\Formatter\Provider\InfoHypermediaFormatterProvider
        arguments:
            - @router
            - @jms_serializer
            - @fos_rest.routing.loader.controller
            - @tms_rest.request.param_reader_provider
            - @tms_rest.request.provider
        tags:
            - { name: tms_rest.formatter.provider, id: info }
