services:
    tms_rest.listeners.param_fetcher:
        class: Tms\Bundle\RestBundle\EventListener\ParamFetcherListener
        arguments: ["@tms_rest.configuration_param_fetcher", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 4 }
