parameters:
    tms_rest.criteria_builder.class: Tms\Bundle\RestBundle\Criteria\CriteriaBuilder
    tms_rest.orderby_builder.class: Tms\Bundle\RestBundle\OrderBy\OrderByBuilder
    tms_rest.entity_handler.class: Tms\Bundle\RestBundle\EntityHandler\EntityHandler

services:
    tms_rest.criteria_builder:
        class: %tms_rest.criteria_builder.class%

    tms_rest.orderby_builder:
        class: %tms_rest.orderby_builder.class%

    tms_rest.entity_handler:
        class: %tms_rest.entity_handler.class%
