parameters:
    tms_rest.criteria_builder.class:            Tms\Bundle\RestBundle\Criteria\CriteriaBuilder
    tms_rest.sort_builder.class:                Tms\Bundle\RestBundle\Sort\SortBuilder
    tms_rest.entity_handler.class:              Tms\Bundle\RestBundle\EntityHandler\EntityHandler
    tms_rest.event_listener.link_request.class: Tms\Bundle\RestBundle\EventListener\LinkRequestListener

services:
    tms_rest.criteria_builder:
        class: %tms_rest.criteria_builder.class%
        arguments: [%tms_rest.configuration%]

    tms_rest.sort_builder:
        class: %tms_rest.sort_builder.class%

    tms_rest.entity_handler:
        class: %tms_rest.entity_handler.class%

    kernel.listener.link_request_listener:
        class: %tms_rest.event_listener.link_request.class%
        arguments: [@controller_resolver, @router]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
