parameters:
    tms_rest.criteria_builder.class:              Tms\Bundle\RestBundle\Criteria\CriteriaBuilder
    tms_rest.sort_builder.class:                  Tms\Bundle\RestBundle\Sort\SortBuilder
    tms_rest.entity_handler.class:                Tms\Bundle\RestBundle\EntityHandler\EntityHandler
    tms_rest.event_listener.link_request.class:   Tms\Bundle\RestBundle\EventListener\LinkRequestListener
    tms_rest.formatter.factory.class:             Tms\Bundle\RestBundle\Factory\FormatterFactory
    tms_rest.request.param_reader_provider.class: Tms\Bundle\RestBundle\Request\ParamReaderProvider
    tms_rest.request.provider.class:              Tms\Bundle\RestBundle\Request\RequestProvider

services:
    tms_rest.configuration_param_fetcher:
        class: Tms\Bundle\RestBundle\ConfigurationParamFetcher
        arguments: [%tms_rest.configuration%]

    tms_rest.criteria_builder:
        class: %tms_rest.criteria_builder.class%
        arguments: [%tms_rest.configuration%]

    tms_rest.sort_builder:
        class: %tms_rest.sort_builder.class%

    tms_rest.entity_handler:
        class: %tms_rest.entity_handler.class%

    tms_rest.formatter.factory:
        class: %tms_rest.formatter.factory.class%

    tms_rest.request.param_reader_provider:
        class: %tms_rest.request.param_reader_provider.class%
        arguments: [@service_container]

    tms_rest.request.provider:
        class: %tms_rest.request.provider.class%
        arguments: [@service_container]
